"""Combine robust 1m waterfall rules into a portfolio-style replay.

The input is a trade CSV generated by discover_waterfall_patterns.py. Each row
already contains one rule's entry/exit simulation. This script answers the next
practical question: after de-duplicating rules, enforcing same-symbol position
conflicts, and applying cooldowns, what is the real combined signal stream?
"""
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


DEFAULT_PRIORITY = [
    "robust_downtrend_range_flush_1m",
    "robust_downtrend_upper_break_1m",
    "downtrend_deep_strong_sell_1m",
    "range_low_runup_break_1m",
    "robust_other_pullback_dump_1m",
    "robust_post_pump_red_sell_1m",
    "robust_post_pump_strong_sell_1m",
    "robust_momentum_uptrend_dump_1m",
    "robust_momentum_lower_wick_dump_1m",
    "post_pump_strong_sell_control_1m",
]


@dataclass(frozen=True)
class ComboConfig:
    name: str
    cooldown_min: int
    allow_after_stop_min: int
    min_gap_same_family_min: int
    max_trades_per_symbol_day: int
    rules: tuple[str, ...]


CONFIGS = [
    ComboConfig("combo_balanced_2h", 120, 240, 60, 3, tuple(DEFAULT_PRIORITY)),
    ComboConfig("combo_fast_1h", 60, 180, 30, 4, tuple(DEFAULT_PRIORITY)),
    ComboConfig(
        "combo_quality_4h",
        240,
        360,
        120,
        2,
        (
            "robust_downtrend_range_flush_1m",
            "robust_downtrend_upper_break_1m",
            "range_low_runup_break_1m",
            "robust_other_pullback_dump_1m",
            "robust_post_pump_red_sell_1m",
            "robust_momentum_uptrend_dump_1m",
        ),
    ),
    ComboConfig(
        "combo_recent_stable",
        120,
        240,
        60,
        3,
        (
            "robust_downtrend_range_flush_1m",
            "robust_downtrend_upper_break_1m",
            "robust_other_pullback_dump_1m",
            "robust_post_pump_red_sell_1m",
            "robust_post_pump_strong_sell_1m",
            "robust_momentum_uptrend_dump_1m",
        ),
    ),
    ComboConfig(
        "combo_recent_core_2h",
        120,
        240,
        60,
        3,
        (
            "robust_downtrend_range_flush_1m",
            "robust_downtrend_upper_break_1m",
            "robust_other_pullback_dump_1m",
            "robust_post_pump_red_sell_1m",
            "robust_momentum_uptrend_dump_1m",
        ),
    ),
    ComboConfig(
        "combo_recent_core_4h",
        240,
        360,
        120,
        2,
        (
            "robust_downtrend_range_flush_1m",
            "robust_downtrend_upper_break_1m",
            "robust_other_pullback_dump_1m",
            "robust_post_pump_red_sell_1m",
            "robust_momentum_uptrend_dump_1m",
        ),
    ),
    ComboConfig(
        "combo_recent_quality_2h",
        120,
        240,
        60,
        3,
        (
            "robust_downtrend_range_flush_1m",
            "robust_downtrend_upper_break_1m",
            "robust_other_pullback_dump_1m",
            "robust_post_pump_red_sell_1m",
        ),
    ),
    ComboConfig(
        "combo_recent_high_pf_2h",
        120,
        240,
        90,
        2,
        (
            "robust_downtrend_range_flush_1m",
            "robust_downtrend_upper_break_1m",
            "robust_other_pullback_dump_1m",
        ),
    ),
]


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    trades = pd.read_csv(args.trades)
    if trades.empty:
        raise SystemExit("empty trades file")
    for col in ("signal_time", "entry_time", "exit_time"):
        trades[col] = pd.to_numeric(trades[col], errors="coerce").astype("int64")
    trades = trades.sort_values(["entry_time", "symbol", "rule"]).reset_index(drop=True)

    rows = []
    selected_by_config: dict[str, pd.DataFrame] = {}
    for config in CONFIGS:
        selected = replay_combo(trades, config)
        selected_by_config[config.name] = selected
        rows.append({"config": config.name, **metrics(selected)})
        rows.extend(period_metrics(selected, config.name))

    summary = pd.DataFrame(rows)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    summary_path = out_dir / f"waterfall_combo_summary_{stamp}.csv"
    report_path = out_dir / f"waterfall_combo_report_{stamp}.md"
    detail_paths: dict[str, str] = {}
    for name, selected in selected_by_config.items():
        path = out_dir / f"waterfall_combo_{name}_{stamp}.csv"
        selected.to_csv(path, index=False)
        detail_paths[name] = str(path)
    summary.to_csv(summary_path, index=False)
    report_path.write_text(render_report(summary, selected_by_config), encoding="utf-8")
    print(json.dumps({"summary": str(summary_path), "report": str(report_path), "details": detail_paths}, ensure_ascii=False), flush=True)
    return 0


def replay_combo(trades: pd.DataFrame, config: ComboConfig) -> pd.DataFrame:
    priority = {rule: i for i, rule in enumerate(config.rules)}
    df = trades[trades["rule"].isin(priority)].copy()
    if df.empty:
        return df
    df["priority"] = df["rule"].map(priority)
    # Same symbol and same minute can be emitted by multiple rules. Keep the
    # highest-priority rule; this approximates one actionable push/entry.
    df = (
        df.sort_values(["entry_time", "symbol", "priority", "ret"], ascending=[True, True, True, False])
        .drop_duplicates(["symbol", "entry_time"], keep="first")
        .reset_index(drop=True)
    )

    active_until: dict[str, int] = {}
    cooldown_until: dict[str, int] = {}
    family_cooldown: dict[tuple[str, str], int] = {}
    symbol_day_count: dict[tuple[str, str], int] = {}
    selected: list[pd.Series] = []

    for _, row in df.sort_values(["entry_time", "priority"]).iterrows():
        symbol = str(row["symbol"])
        family = str(row["family"])
        entry_time = int(row["entry_time"])
        exit_time = int(row["exit_time"])
        day = pd.to_datetime(entry_time, unit="ms").strftime("%Y-%m-%d")
        day_key = (symbol, day)
        family_key = (symbol, family)

        if entry_time < active_until.get(symbol, -1):
            continue
        if entry_time < cooldown_until.get(symbol, -1):
            continue
        if entry_time < family_cooldown.get(family_key, -1):
            continue
        if symbol_day_count.get(day_key, 0) >= config.max_trades_per_symbol_day:
            continue

        selected.append(row)
        symbol_day_count[day_key] = symbol_day_count.get(day_key, 0) + 1
        active_until[symbol] = exit_time
        cool = config.cooldown_min * 60_000
        if str(row["exit_reason"]) == "stop":
            cool = max(cool, config.allow_after_stop_min * 60_000)
        cooldown_until[symbol] = exit_time + cool
        family_cooldown[family_key] = exit_time + config.min_gap_same_family_min * 60_000

    out = pd.DataFrame(selected)
    if out.empty:
        return out
    out = out.drop(columns=["priority"], errors="ignore").sort_values("entry_time").reset_index(drop=True)
    out["entry_time_iso"] = pd.to_datetime(out["entry_time"], unit="ms").dt.strftime("%Y-%m-%d %H:%M")
    out["exit_time_iso"] = pd.to_datetime(out["exit_time"], unit="ms").dt.strftime("%Y-%m-%d %H:%M")
    return out


def metrics(df: pd.DataFrame) -> dict[str, Any]:
    if df.empty:
        return empty_metrics()
    span_days = max(1.0, (float(df["entry_time"].max()) - float(df["entry_time"].min())) / 86_400_000)
    pos = float(df.loc[df["ret"] > 0, "ret"].sum())
    neg = float(-df.loc[df["ret"] < 0, "ret"].sum())
    return {
        "period": "all",
        "trades": int(len(df)),
        "per_day": round(float(len(df) / span_days), 3),
        "symbols": int(df["symbol"].nunique()),
        "win_rate": pct((df["ret"] > 0).mean()),
        "avg_ret": pct(df["ret"].mean()),
        "median_ret": pct(df["ret"].median()),
        "profit_factor": round(pos / neg, 3) if neg > 0 else None,
        "median_mae": pct(df["mae"].median()),
        "p80_mae": pct(df["mae"].quantile(0.8)),
        "median_mfe": pct(df["mfe"].median()),
        "p80_mfe": pct(df["mfe"].quantile(0.8)),
        "big3_rate": pct((df["ret"] >= 0.03).mean()),
        "big5_rate": pct((df["ret"] >= 0.05).mean()),
        "big10_rate": pct((df["ret"] >= 0.10).mean()),
        "stop_rate": pct((df["exit_reason"] == "stop").mean()),
        "median_hold_min": round(float(df["hold_min"].median()), 2),
    }


def period_metrics(df: pd.DataFrame, config_name: str) -> list[dict[str, Any]]:
    if df.empty:
        return []
    dt = pd.to_datetime(df["entry_time"], unit="ms")
    max_dt = dt.max()
    masks = {
        "holdout_202604+": dt >= pd.Timestamp("2026-04-01"),
        "recent180": dt >= max_dt - pd.Timedelta(days=180),
        "recent90": dt >= max_dt - pd.Timedelta(days=90),
    }
    rows = []
    for name, mask in masks.items():
        row = metrics(df.loc[mask].copy())
        row["period"] = name
        row["config"] = config_name
        rows.append(row)
    return rows


def empty_metrics() -> dict[str, Any]:
    return {
        "period": "all",
        "trades": 0,
        "per_day": 0.0,
        "symbols": 0,
        "win_rate": 0.0,
        "avg_ret": 0.0,
        "median_ret": 0.0,
        "profit_factor": None,
        "median_mae": 0.0,
        "p80_mae": 0.0,
        "median_mfe": 0.0,
        "p80_mfe": 0.0,
        "big3_rate": 0.0,
        "big5_rate": 0.0,
        "big10_rate": 0.0,
        "stop_rate": 0.0,
        "median_hold_min": 0.0,
    }


def render_report(summary: pd.DataFrame, selected_by_config: dict[str, pd.DataFrame]) -> str:
    lines = ["# Waterfall Combo Backtest", ""]
    show = summary.copy()
    lines.append("## Summary")
    lines.append(show.to_markdown(index=False))
    lines.append("")
    lines.append("## Rule Mix")
    for name, df in selected_by_config.items():
        lines.append("")
        lines.append(f"### {name}")
        if df.empty:
            lines.append("No trades.")
            continue
        mix = df.groupby(["rule", "family"]).agg(
            trades=("symbol", "size"),
            symbols=("symbol", "nunique"),
            avg_ret=("ret", lambda x: pct(x.mean())),
            pf=("ret", profit_factor),
            win_rate=("ret", lambda x: pct((x > 0).mean())),
        ).reset_index().sort_values("trades", ascending=False)
        lines.append(mix.to_markdown(index=False))
    return "\n".join(lines) + "\n"


def profit_factor(ret: pd.Series) -> float | None:
    pos = float(ret[ret > 0].sum())
    neg = float(-ret[ret < 0].sum())
    return round(pos / neg, 3) if neg > 0 else None


def pct(value: Any) -> float:
    if value is None or not np.isfinite(value):
        return float("nan")
    return round(float(value) * 100.0, 3)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--trades", required=True)
    parser.add_argument("--out-dir", default="backend/storage/ml/waterfall_combo")
    return parser.parse_args(argv)


if __name__ == "__main__":
    raise SystemExit(main())
